corrige_aqui/atividades/urls.py
from django.urls import path

from . import views

app_name = "atividades"
urlpatterns = [
    path("", views.index, name="index"),
    path("adicionar-ou-listar/", views.adicionar_ou_listar_atividade, name="adicionar-ou-listar"),
    path("listar-alunos-do-repositorio/", views.listar_alunos_do_repositorio, name="listar-alunos-do-repositorio"),
    path("logs-aluno", views.logs_aluno, name="logs-aluno"),
    path("adicionar/", views.adicionar_atividade, name="adicionar-atividade"),
    path("aluno/", views.mostrar_repositorios, name="mostrar-repositorios"),
    path("aluno/adicionar/", views.adicionar_repositorio, name="adicionar-repositorio"),
    path("aluno/resultado/", views.pegar_resultados, name="pegar-resultados"),
]

corrige_aqui/corrige_aqui/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include("plataforma.urls")),
    path('atividades/', include("atividades.urls")),
    path('admin/', admin.site.urls),
]

corrige_aqui/atividades/models.py
from django.db import models
import jsonfield


class Turma(models.Model):
    nome = models.CharField(max_length=7, default='turma', editable=False)


class Questao(models.Model):
    repo_name = models.CharField(max_length=50)
    enunciado = models.TextField()
    titulo = models.TextField()
    casos_de_teste = jsonfield.JSONField(default=dict)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)


class Aluno(models.Model):
    repo_name = models.CharField(max_length=50)
    nota = models.IntegerField()


class Restultados(models.Model):
    resultados_incorretos = jsonfield.JSONField(default=dict)
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)


class AlunoTurma(models.Model):
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)
    aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE)

corrige_aqui/atividades/views.py
from ast import literal_eval
from django.shortcuts import render, redirect
from django.conf import settings
from .models import Aluno, AlunoTurma, Questao, Turma, Restultados

import os, shutil, datetime, unicodedata, re, base64
import xml.etree.ElementTree as ET
import requests

def index(request):
    return render(request, "atividades/templates/index.html", {})


def adicionar_ou_listar_atividade(request):
    questao = Questao.objects.last()
    return render(request, "atividades/templates/adicionar-ou-listar.html", {"questao": questao})


def listar_alunos_do_repositorio(request):
    turma = Turma.objects.last()
    alunos_turma = AlunoTurma.objects.filter(turma=turma).values_list('aluno', flat=True)
    alunos = Aluno.objects.filter(pk__in=alunos_turma)
    questao = Questao.objects.get(turma_id=turma.id)

    context = {
        "turma": turma,
        "alunos": alunos,
        "questao": questao,
    }

    return render(request, "atividades/templates/listar-alunos-repo.html", context)


def logs_aluno(request):
    aluno_id = request.POST['aluno']
    aluno = Aluno.objects.get(id=aluno_id)
    resultados_querry = Restultados.objects.filter(aluno_id=aluno.id)

    resultados_incorretos = []
    for resultados in resultados_querry:
        resultados_incorretos.append(literal_eval(resultados.resultados_incorretos))


    repo_name = aluno.repo_name.split("https://github.com/",1)[1]

    response = requests.get(
        f"https://api.github.com/repos/{repo_name}/commits",
    )

    response = response.json()
    numero_de_commits = len(response) - 1

    response_data_from_repository = requests.get(
        f"https://api.github.com/repos/{repo_name}",
    )
    response_data_from_repository = response_data_from_repository.json()

    is_fork = 0
    if "parent" in response_data_from_repository:
        is_fork = 1

    context = {
        "aluno": aluno,
        "numero_de_commits": numero_de_commits,
        "is_fork": is_fork,
        "resultados_incorretos": resultados_incorretos,
    }

    return render(request, "atividades/templates/logs-aluno.html", context)


def criar_arquivo_de_testes(caso_de_teste):

    test_template = """
def test_case_{index}():
    input_data = "{input_data}"
    expected_result = "{expected_result}"
    cast_type = type(expected_result)

    result = subprocess.run(
        "./main",
        input=input_data.encode(),
        stdout=subprocess.PIPE,  
    )
    assert cast_type(result.stdout.decode()) == expected_result
    """

    test_code = ""
    for index, test_data in enumerate(caso_de_teste):
        input_data_tuple = test_data["input"]
        list_of_strings = [str(value) for value in input_data_tuple]
        input_data = "".join(list_of_strings)
        expected_result = test_data["expected_output"]
        test_code += test_template.format(index=index, input_data=input_data, expected_result=expected_result)

    
    with open("./arquivos-para-github/tmp/test_file.py", "w") as file:
        file.write("import subprocess\n\n")
        file.write(test_code)


def criar_readme(enunciado):
    with open("./arquivos-para-github/tmp/README.md", "w") as file:
        file.write(enunciado)


def criar_repositorio(linguagem, repositorio):
    path_linguagem = "./arquivos-para-github/" + linguagem
    path_temp = "./arquivos-para-github/tmp"
    path_create_repo = "./arquivos-para-github/criar-repositorio-python.py"
    
    shutil.copytree(path_linguagem, path_temp, dirs_exist_ok = True)
    shutil.copy(path_create_repo, path_temp + "/criar-repositorio-python.py")
    
    os.system("python ./arquivos-para-github/criar-repositorio-python.py " + repositorio)


def adicionar_atividade(request):
    if request.method == 'POST':
        repositorio = request.POST['repositorio']
        enunciado = request.POST['descricao']
        linguagem = request.POST['linguagem']

        titulos = (request.POST.getlist('titulo'))
        entradas = (request.POST.getlist('entrada'))
        saidas = (request.POST.getlist('saida'))
        casos_de_teste = []
        for i in range(0, len(titulos)):
            teste = {"titulo": titulos[i], "input": entradas[i], "expected_output": saidas[i], "nome_funcao": f"test_case_{i}"}
            casos_de_teste.append(teste)


        repo_name = repositorio.replace(" ", "-") + "-" + str(datetime.datetime.now().strftime('%d-%m-%y-%H-%M-%S.%f'))
        repo_name = unicodedata.normalize('NFKD', repo_name).encode('ASCII', 'ignore').decode('ASCII')

        turma = Turma.objects.last()
        Questao.objects.create(repo_name=repo_name, enunciado=enunciado, titulo="titulo", casos_de_teste=casos_de_teste, turma=turma)

        
        criar_arquivo_de_testes(caso_de_teste=casos_de_teste)
        criar_readme(enunciado)
        criar_repositorio(linguagem, repo_name)

        return redirect(settings.BASE_URL + 'atividades/') 
    return render(request, 'templates/index.html')


def mostrar_repositorios(request):
    repositorios = Questao.objects.all()
    repositorio = Aluno.objects.last()

    context = {
        "repositorios": repositorios,
        "repositorio": repositorio
    }
    return render(request, "atividades/templates/listagem-repositorios.html", context)


def adicionar_repositorio(request):
    aluno = Aluno.objects.create(repo_name=request.POST['repositorio'], nota=0)
    turma = Turma.objects.last()
    AlunoTurma.objects.create(turma=turma, aluno=aluno)
    return redirect(settings.BASE_URL + 'atividades/aluno/') 


def pegar_resultados(request):
    aluno = Aluno.objects.last()
    questao = Questao.objects.last()
    resultados_class = Restultados.objects.filter(aluno_id=aluno.id, questao_id=questao.id)
    casos_de_teste = questao.casos_de_teste
    repo_name = aluno.repo_name
    repo_name = repo_name.split("github.com/", 1)[1]

    response = requests.get(
        f"https://api.github.com/repos/{repo_name}/contents/results.xml",
    )


    if response.status_code == 200:
        data = response.json()
        file_content = data['content']

        file_content_encoding = data.get('encoding')
        if file_content_encoding == 'base64':
            file_content = base64.b64decode(file_content).decode()

        padrao_falhas = r'failures=\"([^\"]*)\"'
        padrao_testes = r'tests=\"([^\"]*)\"'
        correspondencias_falhas = re.search(padrao_falhas, file_content)
        correspondencias_testes = re.search(padrao_testes, file_content)

        if correspondencias_falhas:
            total_falhas = correspondencias_falhas.group(1)

        if correspondencias_testes:
            total_testes = correspondencias_testes.group(1)
        print(f"total falhas {total_falhas}, total testes {total_testes}")
        testes_corretos = int(total_testes) - int(total_falhas)
        resultado = (testes_corretos / int(total_testes)) * 100
        resultado = round(resultado)
        # Ler xml e pegar resultados
        tree = ET.fromstring(file_content)
        testsuite = tree.find("testsuite")

        resultados_testes = {}

        for testcase in testsuite.findall("testcase"):
            if testcase.find("failure") is not None:
                nome_caso = testcase.get("name")
                resultado_esperado = testcase.find("failure").get("message").split("==")[1].strip()
                resultado_esperado = resultado_esperado.split("\n")[0]
                resultado_esperado = resultado_esperado.replace("'", "")
                valor_passado = testcase.find("failure").get("message").split("==")[0].strip()
                valor_passado = valor_passado.split("assert ")[1]
                valor_passado = valor_passado.replace("'", "")
                titulo = casos_de_teste[int(nome_caso[-1])]["titulo"]
                
                print(f"Nome do caso: {nome_caso}")
                print(f"Resultado esperado: {resultado_esperado}")
                print(f"Valor passado: {valor_passado}")
                print("-" * 40)
                resultados_testes[nome_caso] = {"titulo": titulo, "resultado_esperado": resultado_esperado, "valor_passado": valor_passado}
                print(resultados_testes)
                

        if aluno.nota < resultado:
            aluno.nota = resultado
            if resultados_class == None:
                Restultados.objects.create(resultados_testes, aluno, questao)
            else:
                resultados_class.resultados_incorretos = resultados_testes
                resultados_class.save()
            aluno.save()
    else:
        print(f"Error: {response.status_code}")

    context = {
        "aluno": aluno,
        "resultados_testes": resultados_testes
    }
    return render(request, 'atividades/templates/resultados-visao-aluno.html', context)

  

corrige_aqui/atividades/templates/adicionar-ou-listar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repositórios</title>
</head>
<body>
    {% if questao %}
        <h2>Listar Resultados do repositório: </h2>
        <h3>Resultados para o repositório: 
        <form action="{% url 'atividades:listar-alunos-do-repositorio' %}" method="post">
            {% csrf_token %}
            <p>{{questao.repo_name}}: <button type="submit">Listar alunos</button></p>
        </form>
    {% endif %}

    <form method="post" action="{% url 'atividades:index' %}">
        {% csrf_token %}
        <button type="submit">Adicionar Nova Atividade</button>
    </form>
</body>
</html>

corrige_aqui/atividades/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Questão</title>
</head>
<body>
    <h1>Formulário de Questão</h1>
    <form method="post" action="{% url 'atividades:adicionar-atividade' %}">
        {% csrf_token %}
        <div class="modal-body">
                      
          <div id="inputContainer" class="containerPairs py-3">
            <label for="repositorio">Nome do repositório</label>
            <input type="text" name="repositorio"></input>
            
            <label for="linguagem">Linguagem:</label>
            <select name="linguagem" id="linguagem">
              <option value="c">c</option>
            </select> 
            <br>
            <label for="descricao">Descrição do problema:</label>
            <textarea name="descricao" id="descricao" cols="30" rows="10"></textarea>

            <div class="form-group input-pair">
              <input type="text" id="titulo" name="titulo" df-titulo  placeholder="Título">
              <input type="text" id="entrada" name="entrada" df-entrada placeholder="Entrada">
              <input type="text" id="saida" name="saida" df-saida placeholder="Saída Esperada">
            </div>     

          </div> 
            <div class="d-flex justify-content-end">
              <button type="button" class="btn btn-success mt-3" id="addInput" onclick="adicionarInputGithub(this);">Adicionar casos de teste</button>
              <button type="button" class="btn btn-success mt-3" id="removeInput" onclick="removerInputGithub(this);">Remover casos de teste</button>
            </div>
        </div>
        <button type="submit">Enviar</button>
    </form>
</body>
</html>

<script>
    function adicionarInputGithub(params) {
      const inputContainer = document.getElementById("inputContainer");
      const inputPair = document.querySelector(".input-pair");

      const newInputPair = inputPair.cloneNode(true);
      newInputPair.innerHTML = `<input type="text" id="titulo${Math.random().toString(16).slice(2)} " name="titulo" df-titulo${Math.random().toString(16).slice(2)}  placeholder="Título">
                          <input type="text" id="entrada${Math.random().toString(16).slice(2)} " name="entrada" df-entrada${Math.random().toString(16).slice(2)} placeholder="Entrada">
                          <input type="text" id="saida${Math.random().toString(16).slice(2)} " name="saida" df-saida${Math.random().toString(16).slice(2)} placeholder="Saída Esperada">`
      
      inputContainer.appendChild(newInputPair);
    
    }

    // TODO: acertar a lógica para deletar os valores do drawflowJson baseado nos id's dos inputs que são deletados na classe removerInputGithub()
    /* function removeValoresDosTestesApagados(html) {
      var htmlString = html.outerHTML
      const regex = /df-(.*?)=/g;
      const substrings = [];
      let match;

      while ((match = regex.exec(htmlString)) !== null) {
          substrings.push(match[1]);
      }

      var json_string = document.getElementById('json-element').value=JSON.stringify(editor.export(), null, 4)
      var drawflowJson = JSON.parse(json_string)
      drawflowJson = drawflowJson['drawflow']['Home']['data']

      Object.values(drawflowJson).forEach(card => {
        if (card['class'] == 'github') {
          var nomesDeValoresParaRemover = Object.keys(card['data'])
          Object.values(nomesDeValoresParaRemover).forEach(nome => {
            if (substrings.includes(nome)) {
              delete card.data[nome]
            }
          })
        }
      })
      console.log(drawflowJson)
    } */
    
    function removerInputGithub(params) {
      const inputContainer = document.getElementById("inputContainer");
      const inputPairs = document.querySelectorAll(".input-pair");
      
      if (inputPairs.length > 1) {
        //removeValoresDosTestesApagados(inputPairs[inputPairs.length - 1]);
        inputContainer.removeChild(inputPairs[inputPairs.length - 1]);
      }
    }
    
</script> 

corrige_aqui/atividades/templates/listagem-repositorios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repositórios</title>
</head>
<body>
    <h4>Faça um clone do repositório abaixo</h4>
    {% for repositorio in repositorios%}
        <a href="https://github.com/SilasTests/{{repositorio.repo_name}}" target="_blank">{{repositorio.repo_name}}</a>
        <br>
    {% endfor %}
    <br>
    <br>
    <h4>Cole a url do seu repositório.</h4>
    {% if repositorio %}
        <p>Você já adicionou o repositório: <a href="{{repositorio.repo_name}}" target="_blank">{{repositorio.repo_name}}</a></p>
        <p>Veja seus resultados: </p>
        <form method="post" action="{% url 'atividades:pegar-resultados' %}">
            {% csrf_token %}
            <button type="submit">Resultados</button>
        </form>
    {% endif %}

    <form method="post" action="{% url 'atividades:adicionar-repositorio' %}">
        {% csrf_token %}   
        <label for="repositorio">Nome do repositório</label>
        <input type="text" name="repositorio"></input>
        <button type="submit">Enviar</button>
    </form>

</body>
</html>

corrige_aqui/atividades/templates/listar-alunos-repo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repositórios</title>
</head>
<body>
    <h2>Alunos da turma: {{turma.nome}}</h2>
    {% if alunos %}
        {% for aluno in alunos %}
            <h3>{{aluno.repo_name}}</h3>
            <h3>Nota do Aluno: {{aluno.nota}}</h3>
            <form action="{% url 'atividades:logs-aluno' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="aluno" value="{{aluno.id}}">
                <button type="submit">Ver logs individuais</button>
            </form>
        {% endfor %}
    {% endif %}
</body>
</html>

corrige_aqui/atividades/templates/logs-aluno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repositórios</title>
</head>
<body>
    <h2>Aluno: </h2>
    {% if aluno %}
        <h3>Repositório: {{aluno.repo_name}}</h3>
        <h3>Nota: {{aluno.nota}}</h3>
    {% endif %}

    {% if numero_de_commits %}
        <h3>Numero de commits: {{numero_de_commits}}</h3>
    {% endif %}

    {% if is_fork %}
        <h3>O repositório foi criado a partir de um fork do fornecido pelo professor</h3>
    {% endif %}

    {% if resultados_incorretos %}
        {% for tests in resultados_incorretos %}
            {% for test, valor in tests.items %}
                <p>=================================================</p>
                <h3>O teste correspondente ao {{test}} no arquivo de testes falhou</h3>
                
                <p><strong>Nome do teste: </strong>{{valor.titulo}}</p>
                <p><strong>O valor esperado era: </strong>{{valor.resultado_esperado}}</p>
                <p><strong>O valor passado foi: </strong>{{valor.valor_passado}}</p>
            {% endfor %}
        {% endfor %}
    {% endif %}


</body>
</html>

corrige_aqui/atividades/templates/resultados-visao-aluno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repositórios</title>
</head>
<body>
    {% if aluno %}
        <h1>Resultados para o repositório: <a href="{{aluno.repo_name}}" target="_blank">{{aluno.repo_name}}</a></h1>
        <h3>Nota: {{aluno.nota}}</h3>
    {% endif %}

    {% if resultados_testes|length > 0 %}
        {% for teste, valor in resultados_testes.items %}
            <h5>O teste {{valor.titulo}} falhou.</h5>
            <p>O valor esperado era: {{valor.resultado_esperado}}</p>
            <p>O valor passado foi: {{valor.valor_passado}}</p>
        {% endfor %}
    {% endif %}
</body>
</html>
{'test_case_2': {'titulo': 'Negativo', 'resultado_esperado': '-5', 'valor_passado': '-15'}}